# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

jobs:

- job: build

  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - script: |
      cd POne
      dotnet build
      cd ..
    displayName: 'attempt build'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'publish'
      publishWebProjects: true
    displayName: Compileing a publish

  - task: AzureRmWebAppDeployment@4
    inputs:
      ConnectionType: 'AzureRM'
      azureSubscription: 'Azure subscription 1(c4a1f6b6-1679-4387-966c-d14cfa1952ac)'
      appType: 'webApp'
      WebAppName: 'Mishael-Project-One'
      packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
    displayName: Executeing a publish

- job: test

  pool:
    vmimage: windows-latest

  steps:

  - script: dotnet test ./POneTest --logger trx
    displayName: Executeing tests

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'NUnit'
      testResultsFiles: '**/*.xml'
      failTaskOnFailedTests: true
      testRunTitle: 'Test'
    displayName: Publishing test results

- job: code_analisis

  pool:
    vmimage: windows-latest

  steps:



  